const seriesData = [
  {
    id: "1",
    title: "Put Your Head On My Shoulder",
    rating: "9.6",
    votes: "115,811",
    year: "2019",
    badge: "U/A 13+",
    genre: "Romantic Comedy",
    cast: "Xing Fei, Lin Yi, Tang Xiaotian, Zheng Ying Chen",
    subtitles: "English, Arabic, German and 13 more",
    subsBy: "Lean on Me",
    poster: "https://wallpaperaccess.com/full/4622196.jpg",
    episodes: [
      "https://www.youtube.com/embed/v26sxMBQwOk",
      "https://www.youtube.com/embed/w666oFLq3kQ",
      "https://www.youtube.com/embed/zmc-XUKbMxI",
      "https://www.youtube.com/embed/kckeSRKqux0",
      "https://www.youtube.com/embed/0lPFHApCrZ8",
      "https://www.youtube.com/embed/ZahGONrJGkw",
      "https://www.youtube.com/embed/H6LzJ9TqQuE",
      "https://www.youtube.com/embed/TZk8cvmUxLc",
    ]
  },
  {
    id: "2",
    title: "Judwaa",
    rating: "8.2",
    votes: "52,000",
    year: "2025",
    badge: "U/A 13+",
    genre: "Family Drama, Mystery",
    cast: "Aina Asif, Adnan Raza Mir, Sabreen Hisbani, Zhalay Sarhadi",
    subtitles: "English, Urdu",
    subsBy: "HUM TV Team",
    poster: "https://www.pakdramas.com/wp-content/uploads/2025/02/Pakistani-Drama-Judwaa-Cast-1-BtG87.webp",
    episodes: [
      "https://www.youtube.com/embed/6LCrIRl9kIc",
      "https://www.youtube.com/embed/A1_zn6LVxJE",
      "https://www.youtube.com/embed/yjKbCpKcAME",
      "https://www.youtube.com/embed/VlKsf3QU4dA",
      "https://www.youtube.com/embed/0fpj18BYhjQ",
      "https://www.youtube.com/embed/AvZWlt2Mrds",
      "https://www.youtube.com/embed/WC0CjbLoYXM",
      "https://www.youtube.com/embed/AUY-6RTIdOg",
    ]
  },
  {
    id: "3",
    title: "Ren: The Girl with the Mark",
    rating: "8.6",
    votes: "18,000",
    year: "2016–2024",
    badge: "U/A 13+",
    genre: "Fantasy, Adventure",
    cast: "Sophie Skelton, Duran Fulton Brown, Richard Zeman",
    subtitles: "English",
    subsBy: "Mythica Entertainment",
    poster: "https://i.ytimg.com/vi/TXuc01p1xTs/maxresdefault.jpg",
    episodes: [
      "https://www.youtube.com/embed/DwXrfN_-GuE",
      "https://www.youtube.com/embed/alT7IxwYd6U",
      "https://www.youtube.com/embed/EiHzphCFBqE",
      "https://www.youtube.com/embed/fpj4sQqRNyw",
      "https://www.youtube.com/embed/agVEUnhx1zw",
    ]
  },
  {
    id: "4",
    title: "Hidden Marriage With Boss",
    rating: "7.9",
    votes: "40,000",
    year: "2023",
    badge: "U/A 13+",
    genre: "Romantic Drama",
    cast: "Zhao Yiqin, Wang Yuwen",
    subtitles: "English, Chinese",
    subsBy: "MGTV Team",
    poster: "https://i.ytimg.com/vi/GY4HUW2fH_I/maxresdefault.jpg",
    episodes: [
      "https://www.youtube.com/embed/9oUVZz6OT94",
      "https://www.youtube.com/embed/o266efWdnXQ",
      "https://www.youtube.com/embed/f_SkYPZxXLQ",
      "https://www.youtube.com/embed/swCOD9LF-xU",
      "https://www.youtube.com/embed/ITCjE_w_Jos",
      "https://www.youtube.com/embed/TpOJCnwTx4s",
      "https://www.youtube.com/embed/8fSOMJ8pRNo",
      "https://www.youtube.com/embed/4SIS5WrmY7I",
    ]
  },
  {
    id: "5",
    title: "Amber Girls School",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://www.scrolldroll.com/wp-content/uploads/2024/04/Amber-Girls-School-Indian-Web-Series-Releasing-in-May-2024-750x430.jpg",
    episodes: [
      "https://www.youtube.com/embed/2mFajuKw_zI",
      "https://www.youtube.com/embed/HOoOnuVXo9M",
      "https://www.youtube.com/embed/mNPVXiNX3CI",
    ]
  },
  {
    id: "6",
    title: "My Deskmate",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cdnIjh89JX9eZ2VpHmyoIsKEbha.jpg",
    episodes: [
      "https://www.youtube.com/embed/dtyQvF20Dp0",
      "https://www.youtube.com/embed//rQsbYj-Ecyo",
      "https://www.youtube.com/embed/ziWdn3t5B-8",
      "https://www.youtube.com/embed/Cf20_oW0sjo",
      "https://www.youtube.com/embed//rcUXLGQ0pBA",
      "https://www.youtube.com/embed/zsZzsCprmgM",
      "https://www.youtube.com/embed/FapQdTjoUR4",
      "https://www.youtube.com/embed/tb3uABC86K0",
    ]
  },
  {
    id: "7",
    title: "Tujhpe Main Fida",
    rating: "7.6",
    votes: "1400",
    year: "2024",
    badge: "U/A 13+",
    genre: "Romance,Mystery,Fantasy",
    cast: "Rudhraksh as Marcus,Nikeet As Aira",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://m.media-amazon.com/images/M/MV5BNDRkNmZkY2MtZjg1Zi00ODJlLTlhZjktZGJjYWI3ZmVmNzFmXkEyXkFqcGdeQXVyMTcwNjY4MTg0._V1_FMjpg_UX1000_.jpg",
    episodes: [
      "https://www.youtube.com/embed/vcLMLoXOLvY",
      "https://www.youtube.com/embed/ROt6s3nLVWM",
      "https://www.youtube.com/embed/Gw6EB6uLbrs",
    ]
  },
  {
    id: "8",
    title: "Sensitive Matter",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://static1.moviewebimages.com/wordpress/wp-content/uploads/2023/02/the-vow.jpg",
    episodes: [
      "https://www.youtube.com/embed/ljx7ETuOJmM",
      "https://www.youtube.com/embed/trjuYn3xTQk",
      "https://www.youtube.com/embed/iw0HhUI_dW4",
      "https://www.youtube.com/embed/c7scbluZmVE",
      "https://www.youtube.com/embed/1tqpv2aIFyY",
      "https://www.youtube.com/embed/P7WH3HSEXng",
      "https://www.youtube.com/embed/055nbzOhI9U",
      "https://www.youtube.com/embed/KlPJDVtXyRE",
    ]
  },
  {
    id: "9",
    title: "My girlfriend is an alien",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Romantic Comedy, Sci-fi",
    cast: "Wan peng as Chai Xiaoqi Thassapak Hsu as Fanh Leng",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://wallpaperaccess.com/full/9236623.jpg",
    episodes: [
      "https://www.youtube.com/embed/xcI1Q-rcmto",
      "https://www.youtube.com/embed/Z_1E4dmAxQ0",
      "https://www.youtube.com/embed/5_AaMhd3EB4",
      "https://www.youtube.com/embed/CWCLrsW78yw",
      "https://www.youtube.com/embed/1-PS40BzhSo",
      "https://www.youtube.com/embed/l6uWD98NSL0",
      "https://www.youtube.com/embed/WQRzb--mbuc",
      "https://www.youtube.com/embed/dv2UABjWLTE",
    ]
  },
  {
    id: "10",
    title: "Kamwali Bai",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://i.ytimg.com/vi/9iw_e9M2s0g/maxresdefault.jpg",
    episodes: [
      "https://www.youtube.com/embed/KSs_sfWd5UE?",
      "https://www.youtube.com/embed/KmFdbSZMj2s",
      "https://www.youtube.com/embed/FNaSBz9Z4ik",
      "https://www.youtube.com/embed/TtdRUlNuTnY",
      "https://www.youtube.com/embed/7HbVyriw3Qw",
      "https://www.youtube.com/embed/uZUPjaJKJxk",
     
    ]
  },
  {
    id: "11",
    title:"Outlier",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://www.soundtrack.net/img/movie/61972.jpg",
    episodes: [
      "https://www.youtube.com/embed/nJUZl-Mv3-w",
      "https://www.youtube.com/embed/QcBzWrB-WLk",
      "https://www.youtube.com/embed/WBhfMTjH0K0",
      "https://www.youtube.com/embed/jgosV3dat_0",
      "https://www.youtube.com/embed/vWrfkQqR7L4",
      "https://www.youtube.com/embed/JvmoH6ULPlk",
      "https://www.youtube.com/embed/CEzoKdUE65E",
      "https://www.youtube.com/embed/H2KCOqRUbXY",
     
    ]
  },
  {
    id: "11",
    title:"Outlier",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Charlotte Wangel,Noah Kudahl Hendriksen",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://www.soundtrack.net/img/movie/61972.jpg",
    episodes: [
      "https://www.youtube.com/embed/nJUZl-Mv3-w",
      "https://www.youtube.com/embed/QcBzWrB-WLk",
      "https://www.youtube.com/embed/WBhfMTjH0K0",
      "https://www.youtube.com/embed/jgosV3dat_0",
      "https://www.youtube.com/embed/vWrfkQqR7L4",
      "https://www.youtube.com/embed/JvmoH6ULPlk",
      "https://www.youtube.com/embed/CEzoKdUE65E",
      "https://www.youtube.com/embed/H2KCOqRUbXY",
     
    ]
  },

  {
    id: "12",
    title:"I Am Not Robot",
    rating: "8.0",
    votes: "30,000",
    year: "2017-18",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Yoo Seung-ho, Chae-bin, Uhm Ki-joon",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://image.tmdb.org/t/p/original/vKpIUPTiUX0pOdh0N813nHvNczg.jpg",
    episodes: [
      "https://www.youtube.com/embed/f_Lm6z9px30",
      "https://www.youtube.com/embed/HayBNPAhjfQ",
      "https://www.youtube.com/embed/MCgOVsXpIZg",
      "https://www.youtube.com/embed/AF2BCQ9-7hA",
      "https://www.youtube.com/embed/w_BC1dQ9vlo",
      "https://www.youtube.com/embed/YV4GOYny7Wg",
     
     
    ]
  },
  {
    id: "13",
    title:"Hidden Love",
    rating: "8.0",
    votes: "30,000",
    year: "2023",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Lusi Zhao,Zheyuan Chen, Zhang Jiong Min",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://otakukart.com/wp-content/uploads/2023/07/Hidden-love-1.jpg",
    episodes: [
      "https://www.youtube.com/embed/guO5E88iiYA",
      "https://www.youtube.com/embed/Lfg8OOHbEpk",
      "https://www.youtube.com/embed/HDRFx2rtQ8o",
      "https://www.youtube.com/embed/30isL6aisn4",
      "https://www.youtube.com/embed/QtegdxAjaYA",
      "https://www.youtube.com/embed/SvVrsB2_-HM",
      "https://www.youtube.com/embed/rVXkJ2M-lBE",
      "https://www.youtube.com/embed/5P6ANysDGtE",
     
     
    ]
  },
  {
    id: "14",
    title:"Sweet Trap",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Binbin Xie, Miaoyi Zhang, Xu Ning Tian, Yaqi Peng",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://cdn.idntimes.com/content-images/community/2024/02/ge-1fiweaaso-h-3b8f45937247ac56ab357cf5fdf86c43-b740a34b1bfa0e5b74ff466a4da103d3.jpg",
    episodes: [
      "https://www.youtube.com/embed/H84Z-e0Nsmc",
      "https://www.youtube.com/embed/8IiIHi0miOA",
      "https://www.youtube.com/embed/Exfv8Z8OAyY",
      "https://www.youtube.com/embed/u0ZihZvCSvw",
      "https://www.youtube.com/embed/zASsMB2Rmbw",
      "https://www.youtube.com/embed/rM8UBgU4Kso",
      "https://www.youtube.com/embed/0jJ3BsJQQEg",
      "https://www.youtube.com/embed/z6_vxP_r69E",
     
     
    ]
  },
  {
    id: "15",
    title:"Sweet Sweet",
    rating: "8.0",
    votes: "30,000",
    year: "2021",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Yiqin Zhao, Yu He, Yiyi Ding, Liu Yan Cheng",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://i.ytimg.com/vi/Wf3xAGAOlmE/maxresdefault.jpg",
    episodes: [
      "https://www.youtube.com/embed/t7nsVZYQ09I",
      "https://www.youtube.com/embed/xRsFa7hXPmw",
      "https://www.youtube.com/embed/wx4bmE-Stt4",
      "https://www.youtube.com/embed/EcsJkUqsI9Q",
      "https://www.youtube.com/embed/-jBn5a3al5Y",
      "https://www.youtube.com/embed/_zDUVNpr4tk",
      "https://www.youtube.com/embed/x1ZSy39Ogk4",
      "https://www.youtube.com/embed/NLc0e0zXeZE",
     
     
    ]
  },
  {
    id: "16",
    title:"Live On",
    rating: "8.0",
    votes: "30,000",
    year: "2020",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age,Romance",
    cast: "Jung Da-bin, Hwang Min-hyun, Noh Jong-hyun",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://media.themoviedb.org/t/p/w440_and_h660_face/dop9lujlpXaIGZImoTgUteHXt7a.jpg",
    episodes: [
      "https://www.youtube.com/embed/htYQwssezhE",
      "https://www.youtube.com/embed/fyPk14ZZkd8",
      "https://www.youtube.com/embed/PFBSRBaDXiQ",
      "https://www.youtube.com/embed/uX6VnHj2Gws",
      "https://www.youtube.com/embed/i8LbZ5fLT9o",
      "https://www.youtube.com/embed/SVPfYM7lSfM",
      "https://www.youtube.com/embed/EuHOIs1_huY",
      "https://www.youtube.com/embed/e8wHeEXQOU8",
     
     
    ]
  },
  {
    id: "17",
    title:"Sisters",
    rating: "8.0",
    votes: "30,000",
    year: "2022",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Riddhi Sen, Madhurima Roy, Shivani Raghuvanshi",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://www.newsbharati.com/Encyc/2022/10/12/maxresdefault-(1)_202210121151327462_H@@IGHT_400_W@@IDTH_1280.jpg",
    episodes: [
      "https://www.youtube.com/embed/uO5PBXJLYuc",
      "https://www.youtube.com/embed/KflwDKBH2T4",
      "https://www.youtube.com/embed/2HaC5Uq8E9Q",
      "https://www.youtube.com/embed/1OFhjatwLh0",
      "https://www.youtube.com/embed/Ob_sfxmfjMw",
      "https://www.youtube.com/embed/FnbaW_d40-Q",
      "https://www.youtube.com/embed/HGKe6Y5aaF4",
      "https://www.youtube.com/embed/O5myIndBEig",
     
     
    ]
  },
  {
    id: "18",
    title:"Aisa Waisa Pyaar",
    rating: "8.0",
    votes: "30,000",
    year: "2021",
    badge: "U/A 13+",
    genre: "Drama, Romance",
    cast: "Ahsaas Channa, Sheeba Chaddha, Saqib Saleem",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://images004-a.media.erosnow.com/IMG_625_352/2021-11-30/20004212.jpg",
    episodes: [
      "https://www.youtube.com/embed/BJpQ_q8dF48",
      "https://www.youtube.com/embed/YmA5H9wc_Eg",
      "https://www.youtube.com/embed/Q7BxcXLTHxM",
      "https://www.youtube.com/embed/hqJqlXNnEyA", 
    ]
  },
  {
    id: "19",
    title:"Baat Pakki",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Romance, Comedy",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://s2.dmcdn.net/v/Xz7Wg1dlYU9LsS3A5/x720",
    episodes: [
      "https://www.youtube.com/embed/_ounzSWlBuM",
      "https://www.youtube.com/embed/wfd48Qn8n4I",
      "https://www.youtube.com/embed/EyswxwZKU1E",
      "https://www.youtube.com/embed/19nc2HBYfP8",
      "https://www.youtube.com/embed/ATah6clue1E",
     
    ]
  },
  
  {
    id: "20",
    title:"Call me bae",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Ananya Panday, Vir Das, Varun Sood",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://bingeddata.s3.amazonaws.com/uploads/2024/09/call-me-bae-review-ananya-panday-being-herself-is-so-much-fun.jpg",
    episodes: [
      "https://www.youtube.com/embed/ev5zuswi4jY",
      "https://www.youtube.com/embed/3mJMTZph1vc",
      "https://www.youtube.com/embed/q5qOCfv-xQ4",
      "https://www.youtube.com/embed/zGJcGolU76g",
      "https://www.youtube.com/embed/7m4kbDnYLcs",
      "https://www.youtube.com/embed//Lrl_3xmwmCw",
      "https://www.youtube.com/embed/ObVdAeobtfM",
      "https://www.youtube.com/embed/QuNbcvYjpH4",
     
     
    ]
  },
  {
    id: "21",
    title:"Dehati Ladke",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Shine Pandey, Saamya Jainn, Raghav Sharma",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://i.gadgets360cdn.com/products/large/Dehati-Ladke-1422x800-1702897042450.jpg?downsize=*:240",
    episodes: [
      "https://www.youtube.com/embed/6tGGF-x4TQA?",
      "https://www.youtube.com/embed/Dx_Nl5bP8nA",
      "https://www.youtube.com/embed/gS3MNVwIkUU",
      "https://www.youtube.com/embed/kphBurfAbHc",
      "https://www.youtube.com/embed/hXFeNyOKwsY",
      "https://www.youtube.com/embed/-aNV8Q1ILFU", 
    ]
  },
  {
    id: "22",
    title:"Naam Namak Nishan",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Varun Sood, Danish Sood, Karan Vohra",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://static.tnn.in/thumb/msid-112503231,thumbsize-381066,width-1280,height-720,resizemode-75/112503231.jpg?quality=100",
    episodes: [
      "https://www.youtube.com/embed/Gs51SQ9PuXs",
      "https://www.youtube.com/embed/VzqgW21wLn4",
      "https://www.youtube.com/embed/g26yAXLv3OI",
      "https://www.youtube.com/embed/_vXqvfD1k-Q",
      "https://www.youtube.com/embed/20lMSIz9COU",
      "https://www.youtube.com/embed/sRkV6MQhflY",
      "https://www.youtube.com/embed/-uCxsmKJRls",
      "https://www.youtube.com/embed/kJA08dIQQq8",
     
     
    ]
  },
  {
    id: "23",
    title:"United Kacche",
    rating: "8.0",
    votes: "30,000",
    year: "2023",
    badge: "U/A 16+",
    genre: "Comedy, Drama",
    cast: "Sunil Grover, Sapna Pabbi, Nikhil Vijay",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://ik.imagekit.io/j83rchiauw/seo_popular_master/202304031137_0feXalHE5LaaiSYb.webp",
    episodes: [
      "https://www.youtube.com/embed/Hk8f5yzUY_M",
    
     
    ]
  },
  {
    id: "24",
    title:"Modern Parivaar",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Kritika Avasthi, Alam Khan",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://i.ytimg.com/vi/s0s692OVj0U/maxresdefault.jpg",
    episodes: [
      "https://www.youtube.com/embed/-PwumQ6UlYE",
      "https://www.youtube.com/embed/TZRXdZG0n_0",
      "https://www.youtube.com/embed/1U0vP8WjyzE",
    ]
  },
  
  {
    id: "25",
    title:"Sunflower",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Crime, Comedy, Thriller",
    cast: "Sunil Grover, Ranvir Shorey, Adah Sharma",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://akm-img-a-in.tosshub.com/sites/ichowk/fb_feed_images/story_image/202106/sunflower-review-sta_061221073255.jpg",
    episodes: [
      "https://www.youtube.com/embed/AWkfxfbNVh8",
      "https://www.youtube.com/embed/81ujr_PtHcA",
      "https://www.youtube.com/embed/qlMq7V_pXvE",
      "https://www.youtube.com/embed/xTVxgqhW5sw",
    ]
  },
  
  {
    id: "26",
    title:"Mentalhood",
    rating: "8.0",
    votes: "30,000",
    year: "2020",
    badge: "U/A 13+",
    genre: "Drama, Comedy",
    cast: " Karisma Kapoor, Sanjay Suri, Shilpa Shukla",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://assets.vogue.in/photos/5ce641814a30b312b413766e/16:9/w_1280,c_limit/Karisma-Kapoor-in-Mentalhood.jpg",
    episodes: [
      "https://www.youtube.com/embed/nktPoHmUNyE",
      "https://www.youtube.com/embed/qJftiLG2raQ",
      "https://www.youtube.com/embed/Xl8qaPGCwqM",
      "https://www.youtube.com/embed/mWvv4HRpZuM",
      "https://www.youtube.com/embed/pxYvwxL9zpc",
      "https://www.youtube.com/embed/FEmlyNRGMKw",
      "https://www.youtube.com/embed/FEmlyNRGMKw",
      "https://www.youtube.com/embed/0UH7iAJ0IZk",
     
     
    ]
  },
    
  {
    id: "27",
    title:"The Bad Seed",
    rating: "8.0",
    votes: "30,000",
    year: "2022",
    badge: "U/A 13+",
    genre: "Drama, Horror",
    cast: "Mckenna Grace, Michelle Morgan, Benjamin Ayres",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://celebmafia.com/wp-content/uploads/2022/06/mckenna-grace-the-bad-seed-returns-photos-and-poster-7.jpg",
    episodes: [
      "https://www.youtube.com/embed/ENyNgK70muI",
      "https://www.youtube.com/embed/F6UMMOa7rLg",
      "https://www.youtube.com/embed/MxDa9xvRYTQ",
      "https://www.youtube.com/embed/TUBmhBho8hM",
      "https://www.youtube.com/embed/dYfMY91syAY",
   
    ]
  },

  {
    id: "28",
    title:"The Bible",
    rating: "8.0",
    votes: "30,000",
    year: "2013",
    badge: "U/A 13+",
    genre: "Drama, Historical",
    cast: "Diogo Morgado, Roma Downey, Darwin Shaw",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://h-o-m-e.org/wp-content/uploads/2023/06/the-bible-series-netflix-1.jpg",
    episodes: [
      "https://www.youtube.com/embed/S_3W9rcwk-w",
      "https://www.youtube.com/embed/8OT5pd5iNpI",
      "https://www.youtube.com/embed/7WeShAJK-VI",
      "https://www.youtube.com/embed/FXrQ57iFkOI",
      "https://www.youtube.com/embed/zjyHgtbUbcM",
      "https://www.youtube.com/embed/nDHb_oD0cNY",
  
    ]
  },
  
  {
    id: "29",
    title:"",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://h-o-m-e.org/wp-content/uploads/2023/06/the-bible-series-netflix-1.jpg",
    episodes: [
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
     
     
    ]
  },
  {
    id: "30",
    title:"",
    rating: "8.0",
    votes: "30,000",
    year: "2024",
    badge: "U/A 13+",
    genre: "Drama, Coming-of-age",
    cast: "Unknown (New Cast)",
    subtitles: "English, Hindi",
    subsBy: "ScrollDroll Team",
    poster: "https://h-o-m-e.org/wp-content/uploads/2023/06/the-bible-series-netflix-1.jpg",
    episodes: [
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
      "https://www.youtube.com/embed/",
     
     
    ]
  },

];

export default seriesData;
